// Code generated by ent, DO NOT EDIT.

package usergroupentitlement

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldEQ(FieldUserID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldEQ(FieldGroupID, v))
}

// FallbackGroupID applies equality check predicate on the "fallback_group_id" field. It's identical to FallbackGroupIDEQ.
func FallbackGroupID(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldEQ(FieldFallbackGroupID, v))
}

// RedeemCodeID applies equality check predicate on the "redeem_code_id" field. It's identical to RedeemCodeIDEQ.
func RedeemCodeID(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldEQ(FieldRedeemCodeID, v))
}

// StartsAt applies equality check predicate on the "starts_at" field. It's identical to StartsAtEQ.
func StartsAt(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldEQ(FieldStartsAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldEQ(FieldExpiresAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldEQ(FieldStatus, v))
}

// ExpiredAt applies equality check predicate on the "expired_at" field. It's identical to ExpiredAtEQ.
func ExpiredAt(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldEQ(FieldExpiredAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldLTE(FieldUserID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldLTE(FieldGroupID, v))
}

// FallbackGroupIDEQ applies the EQ predicate on the "fallback_group_id" field.
func FallbackGroupIDEQ(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldEQ(FieldFallbackGroupID, v))
}

// FallbackGroupIDNEQ applies the NEQ predicate on the "fallback_group_id" field.
func FallbackGroupIDNEQ(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldNEQ(FieldFallbackGroupID, v))
}

// FallbackGroupIDIn applies the In predicate on the "fallback_group_id" field.
func FallbackGroupIDIn(vs ...int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldIn(FieldFallbackGroupID, vs...))
}

// FallbackGroupIDNotIn applies the NotIn predicate on the "fallback_group_id" field.
func FallbackGroupIDNotIn(vs ...int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldNotIn(FieldFallbackGroupID, vs...))
}

// FallbackGroupIDGT applies the GT predicate on the "fallback_group_id" field.
func FallbackGroupIDGT(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldGT(FieldFallbackGroupID, v))
}

// FallbackGroupIDGTE applies the GTE predicate on the "fallback_group_id" field.
func FallbackGroupIDGTE(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldGTE(FieldFallbackGroupID, v))
}

// FallbackGroupIDLT applies the LT predicate on the "fallback_group_id" field.
func FallbackGroupIDLT(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldLT(FieldFallbackGroupID, v))
}

// FallbackGroupIDLTE applies the LTE predicate on the "fallback_group_id" field.
func FallbackGroupIDLTE(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldLTE(FieldFallbackGroupID, v))
}

// RedeemCodeIDEQ applies the EQ predicate on the "redeem_code_id" field.
func RedeemCodeIDEQ(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldEQ(FieldRedeemCodeID, v))
}

// RedeemCodeIDNEQ applies the NEQ predicate on the "redeem_code_id" field.
func RedeemCodeIDNEQ(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldNEQ(FieldRedeemCodeID, v))
}

// RedeemCodeIDIn applies the In predicate on the "redeem_code_id" field.
func RedeemCodeIDIn(vs ...int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldIn(FieldRedeemCodeID, vs...))
}

// RedeemCodeIDNotIn applies the NotIn predicate on the "redeem_code_id" field.
func RedeemCodeIDNotIn(vs ...int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldNotIn(FieldRedeemCodeID, vs...))
}

// RedeemCodeIDGT applies the GT predicate on the "redeem_code_id" field.
func RedeemCodeIDGT(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldGT(FieldRedeemCodeID, v))
}

// RedeemCodeIDGTE applies the GTE predicate on the "redeem_code_id" field.
func RedeemCodeIDGTE(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldGTE(FieldRedeemCodeID, v))
}

// RedeemCodeIDLT applies the LT predicate on the "redeem_code_id" field.
func RedeemCodeIDLT(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldLT(FieldRedeemCodeID, v))
}

// RedeemCodeIDLTE applies the LTE predicate on the "redeem_code_id" field.
func RedeemCodeIDLTE(v int64) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldLTE(FieldRedeemCodeID, v))
}

// RedeemCodeIDIsNil applies the IsNil predicate on the "redeem_code_id" field.
func RedeemCodeIDIsNil() predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldIsNull(FieldRedeemCodeID))
}

// RedeemCodeIDNotNil applies the NotNil predicate on the "redeem_code_id" field.
func RedeemCodeIDNotNil() predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldNotNull(FieldRedeemCodeID))
}

// StartsAtEQ applies the EQ predicate on the "starts_at" field.
func StartsAtEQ(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldEQ(FieldStartsAt, v))
}

// StartsAtNEQ applies the NEQ predicate on the "starts_at" field.
func StartsAtNEQ(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldNEQ(FieldStartsAt, v))
}

// StartsAtIn applies the In predicate on the "starts_at" field.
func StartsAtIn(vs ...time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldIn(FieldStartsAt, vs...))
}

// StartsAtNotIn applies the NotIn predicate on the "starts_at" field.
func StartsAtNotIn(vs ...time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldNotIn(FieldStartsAt, vs...))
}

// StartsAtGT applies the GT predicate on the "starts_at" field.
func StartsAtGT(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldGT(FieldStartsAt, v))
}

// StartsAtGTE applies the GTE predicate on the "starts_at" field.
func StartsAtGTE(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldGTE(FieldStartsAt, v))
}

// StartsAtLT applies the LT predicate on the "starts_at" field.
func StartsAtLT(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldLT(FieldStartsAt, v))
}

// StartsAtLTE applies the LTE predicate on the "starts_at" field.
func StartsAtLTE(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldLTE(FieldStartsAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldLTE(FieldExpiresAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldContainsFold(FieldStatus, v))
}

// ExpiredAtEQ applies the EQ predicate on the "expired_at" field.
func ExpiredAtEQ(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldEQ(FieldExpiredAt, v))
}

// ExpiredAtNEQ applies the NEQ predicate on the "expired_at" field.
func ExpiredAtNEQ(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldNEQ(FieldExpiredAt, v))
}

// ExpiredAtIn applies the In predicate on the "expired_at" field.
func ExpiredAtIn(vs ...time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldIn(FieldExpiredAt, vs...))
}

// ExpiredAtNotIn applies the NotIn predicate on the "expired_at" field.
func ExpiredAtNotIn(vs ...time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldNotIn(FieldExpiredAt, vs...))
}

// ExpiredAtGT applies the GT predicate on the "expired_at" field.
func ExpiredAtGT(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldGT(FieldExpiredAt, v))
}

// ExpiredAtGTE applies the GTE predicate on the "expired_at" field.
func ExpiredAtGTE(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldGTE(FieldExpiredAt, v))
}

// ExpiredAtLT applies the LT predicate on the "expired_at" field.
func ExpiredAtLT(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldLT(FieldExpiredAt, v))
}

// ExpiredAtLTE applies the LTE predicate on the "expired_at" field.
func ExpiredAtLTE(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldLTE(FieldExpiredAt, v))
}

// ExpiredAtIsNil applies the IsNil predicate on the "expired_at" field.
func ExpiredAtIsNil() predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldIsNull(FieldExpiredAt))
}

// ExpiredAtNotNil applies the NotNil predicate on the "expired_at" field.
func ExpiredAtNotNil() predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldNotNull(FieldExpiredAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserGroupEntitlement) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserGroupEntitlement) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserGroupEntitlement) predicate.UserGroupEntitlement {
	return predicate.UserGroupEntitlement(sql.NotPredicates(p))
}
