// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usergroupentitlement"
)

// UserGroupEntitlementUpdate is the builder for updating UserGroupEntitlement entities.
type UserGroupEntitlementUpdate struct {
	config
	hooks    []Hook
	mutation *UserGroupEntitlementMutation
}

// Where appends a list predicates to the UserGroupEntitlementUpdate builder.
func (_u *UserGroupEntitlementUpdate) Where(ps ...predicate.UserGroupEntitlement) *UserGroupEntitlementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserGroupEntitlementUpdate) SetUserID(v int64) *UserGroupEntitlementUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserGroupEntitlementUpdate) SetNillableUserID(v *int64) *UserGroupEntitlementUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserGroupEntitlementUpdate) AddUserID(v int64) *UserGroupEntitlementUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *UserGroupEntitlementUpdate) SetGroupID(v int64) *UserGroupEntitlementUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *UserGroupEntitlementUpdate) SetNillableGroupID(v *int64) *UserGroupEntitlementUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *UserGroupEntitlementUpdate) AddGroupID(v int64) *UserGroupEntitlementUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetFallbackGroupID sets the "fallback_group_id" field.
func (_u *UserGroupEntitlementUpdate) SetFallbackGroupID(v int64) *UserGroupEntitlementUpdate {
	_u.mutation.ResetFallbackGroupID()
	_u.mutation.SetFallbackGroupID(v)
	return _u
}

// SetNillableFallbackGroupID sets the "fallback_group_id" field if the given value is not nil.
func (_u *UserGroupEntitlementUpdate) SetNillableFallbackGroupID(v *int64) *UserGroupEntitlementUpdate {
	if v != nil {
		_u.SetFallbackGroupID(*v)
	}
	return _u
}

// AddFallbackGroupID adds value to the "fallback_group_id" field.
func (_u *UserGroupEntitlementUpdate) AddFallbackGroupID(v int64) *UserGroupEntitlementUpdate {
	_u.mutation.AddFallbackGroupID(v)
	return _u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_u *UserGroupEntitlementUpdate) SetRedeemCodeID(v int64) *UserGroupEntitlementUpdate {
	_u.mutation.ResetRedeemCodeID()
	_u.mutation.SetRedeemCodeID(v)
	return _u
}

// SetNillableRedeemCodeID sets the "redeem_code_id" field if the given value is not nil.
func (_u *UserGroupEntitlementUpdate) SetNillableRedeemCodeID(v *int64) *UserGroupEntitlementUpdate {
	if v != nil {
		_u.SetRedeemCodeID(*v)
	}
	return _u
}

// AddRedeemCodeID adds value to the "redeem_code_id" field.
func (_u *UserGroupEntitlementUpdate) AddRedeemCodeID(v int64) *UserGroupEntitlementUpdate {
	_u.mutation.AddRedeemCodeID(v)
	return _u
}

// ClearRedeemCodeID clears the value of the "redeem_code_id" field.
func (_u *UserGroupEntitlementUpdate) ClearRedeemCodeID() *UserGroupEntitlementUpdate {
	_u.mutation.ClearRedeemCodeID()
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *UserGroupEntitlementUpdate) SetStartsAt(v time.Time) *UserGroupEntitlementUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *UserGroupEntitlementUpdate) SetNillableStartsAt(v *time.Time) *UserGroupEntitlementUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserGroupEntitlementUpdate) SetExpiresAt(v time.Time) *UserGroupEntitlementUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserGroupEntitlementUpdate) SetNillableExpiresAt(v *time.Time) *UserGroupEntitlementUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserGroupEntitlementUpdate) SetStatus(v string) *UserGroupEntitlementUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserGroupEntitlementUpdate) SetNillableStatus(v *string) *UserGroupEntitlementUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *UserGroupEntitlementUpdate) SetExpiredAt(v time.Time) *UserGroupEntitlementUpdate {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *UserGroupEntitlementUpdate) SetNillableExpiredAt(v *time.Time) *UserGroupEntitlementUpdate {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (_u *UserGroupEntitlementUpdate) ClearExpiredAt() *UserGroupEntitlementUpdate {
	_u.mutation.ClearExpiredAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserGroupEntitlementUpdate) SetUpdatedAt(v time.Time) *UserGroupEntitlementUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserGroupEntitlementMutation object of the builder.
func (_u *UserGroupEntitlementUpdate) Mutation() *UserGroupEntitlementMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserGroupEntitlementUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserGroupEntitlementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserGroupEntitlementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserGroupEntitlementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserGroupEntitlementUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usergroupentitlement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserGroupEntitlementUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := usergroupentitlement.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserGroupEntitlement.status": %w`, err)}
		}
	}
	return nil
}

func (_u *UserGroupEntitlementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usergroupentitlement.Table, usergroupentitlement.Columns, sqlgraph.NewFieldSpec(usergroupentitlement.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(usergroupentitlement.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(usergroupentitlement.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(usergroupentitlement.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(usergroupentitlement.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FallbackGroupID(); ok {
		_spec.SetField(usergroupentitlement.FieldFallbackGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFallbackGroupID(); ok {
		_spec.AddField(usergroupentitlement.FieldFallbackGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RedeemCodeID(); ok {
		_spec.SetField(usergroupentitlement.FieldRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRedeemCodeID(); ok {
		_spec.AddField(usergroupentitlement.FieldRedeemCodeID, field.TypeInt64, value)
	}
	if _u.mutation.RedeemCodeIDCleared() {
		_spec.ClearField(usergroupentitlement.FieldRedeemCodeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(usergroupentitlement.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(usergroupentitlement.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usergroupentitlement.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(usergroupentitlement.FieldExpiredAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiredAtCleared() {
		_spec.ClearField(usergroupentitlement.FieldExpiredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usergroupentitlement.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usergroupentitlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserGroupEntitlementUpdateOne is the builder for updating a single UserGroupEntitlement entity.
type UserGroupEntitlementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserGroupEntitlementMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserGroupEntitlementUpdateOne) SetUserID(v int64) *UserGroupEntitlementUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserGroupEntitlementUpdateOne) SetNillableUserID(v *int64) *UserGroupEntitlementUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserGroupEntitlementUpdateOne) AddUserID(v int64) *UserGroupEntitlementUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *UserGroupEntitlementUpdateOne) SetGroupID(v int64) *UserGroupEntitlementUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *UserGroupEntitlementUpdateOne) SetNillableGroupID(v *int64) *UserGroupEntitlementUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *UserGroupEntitlementUpdateOne) AddGroupID(v int64) *UserGroupEntitlementUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetFallbackGroupID sets the "fallback_group_id" field.
func (_u *UserGroupEntitlementUpdateOne) SetFallbackGroupID(v int64) *UserGroupEntitlementUpdateOne {
	_u.mutation.ResetFallbackGroupID()
	_u.mutation.SetFallbackGroupID(v)
	return _u
}

// SetNillableFallbackGroupID sets the "fallback_group_id" field if the given value is not nil.
func (_u *UserGroupEntitlementUpdateOne) SetNillableFallbackGroupID(v *int64) *UserGroupEntitlementUpdateOne {
	if v != nil {
		_u.SetFallbackGroupID(*v)
	}
	return _u
}

// AddFallbackGroupID adds value to the "fallback_group_id" field.
func (_u *UserGroupEntitlementUpdateOne) AddFallbackGroupID(v int64) *UserGroupEntitlementUpdateOne {
	_u.mutation.AddFallbackGroupID(v)
	return _u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_u *UserGroupEntitlementUpdateOne) SetRedeemCodeID(v int64) *UserGroupEntitlementUpdateOne {
	_u.mutation.ResetRedeemCodeID()
	_u.mutation.SetRedeemCodeID(v)
	return _u
}

// SetNillableRedeemCodeID sets the "redeem_code_id" field if the given value is not nil.
func (_u *UserGroupEntitlementUpdateOne) SetNillableRedeemCodeID(v *int64) *UserGroupEntitlementUpdateOne {
	if v != nil {
		_u.SetRedeemCodeID(*v)
	}
	return _u
}

// AddRedeemCodeID adds value to the "redeem_code_id" field.
func (_u *UserGroupEntitlementUpdateOne) AddRedeemCodeID(v int64) *UserGroupEntitlementUpdateOne {
	_u.mutation.AddRedeemCodeID(v)
	return _u
}

// ClearRedeemCodeID clears the value of the "redeem_code_id" field.
func (_u *UserGroupEntitlementUpdateOne) ClearRedeemCodeID() *UserGroupEntitlementUpdateOne {
	_u.mutation.ClearRedeemCodeID()
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *UserGroupEntitlementUpdateOne) SetStartsAt(v time.Time) *UserGroupEntitlementUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *UserGroupEntitlementUpdateOne) SetNillableStartsAt(v *time.Time) *UserGroupEntitlementUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserGroupEntitlementUpdateOne) SetExpiresAt(v time.Time) *UserGroupEntitlementUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserGroupEntitlementUpdateOne) SetNillableExpiresAt(v *time.Time) *UserGroupEntitlementUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserGroupEntitlementUpdateOne) SetStatus(v string) *UserGroupEntitlementUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserGroupEntitlementUpdateOne) SetNillableStatus(v *string) *UserGroupEntitlementUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *UserGroupEntitlementUpdateOne) SetExpiredAt(v time.Time) *UserGroupEntitlementUpdateOne {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *UserGroupEntitlementUpdateOne) SetNillableExpiredAt(v *time.Time) *UserGroupEntitlementUpdateOne {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (_u *UserGroupEntitlementUpdateOne) ClearExpiredAt() *UserGroupEntitlementUpdateOne {
	_u.mutation.ClearExpiredAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserGroupEntitlementUpdateOne) SetUpdatedAt(v time.Time) *UserGroupEntitlementUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserGroupEntitlementMutation object of the builder.
func (_u *UserGroupEntitlementUpdateOne) Mutation() *UserGroupEntitlementMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserGroupEntitlementUpdate builder.
func (_u *UserGroupEntitlementUpdateOne) Where(ps ...predicate.UserGroupEntitlement) *UserGroupEntitlementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserGroupEntitlementUpdateOne) Select(field string, fields ...string) *UserGroupEntitlementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserGroupEntitlement entity.
func (_u *UserGroupEntitlementUpdateOne) Save(ctx context.Context) (*UserGroupEntitlement, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserGroupEntitlementUpdateOne) SaveX(ctx context.Context) *UserGroupEntitlement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserGroupEntitlementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserGroupEntitlementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserGroupEntitlementUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usergroupentitlement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserGroupEntitlementUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := usergroupentitlement.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserGroupEntitlement.status": %w`, err)}
		}
	}
	return nil
}

func (_u *UserGroupEntitlementUpdateOne) sqlSave(ctx context.Context) (_node *UserGroupEntitlement, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usergroupentitlement.Table, usergroupentitlement.Columns, sqlgraph.NewFieldSpec(usergroupentitlement.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserGroupEntitlement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usergroupentitlement.FieldID)
		for _, f := range fields {
			if !usergroupentitlement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usergroupentitlement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(usergroupentitlement.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(usergroupentitlement.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(usergroupentitlement.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(usergroupentitlement.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FallbackGroupID(); ok {
		_spec.SetField(usergroupentitlement.FieldFallbackGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFallbackGroupID(); ok {
		_spec.AddField(usergroupentitlement.FieldFallbackGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RedeemCodeID(); ok {
		_spec.SetField(usergroupentitlement.FieldRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRedeemCodeID(); ok {
		_spec.AddField(usergroupentitlement.FieldRedeemCodeID, field.TypeInt64, value)
	}
	if _u.mutation.RedeemCodeIDCleared() {
		_spec.ClearField(usergroupentitlement.FieldRedeemCodeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(usergroupentitlement.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(usergroupentitlement.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usergroupentitlement.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(usergroupentitlement.FieldExpiredAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiredAtCleared() {
		_spec.ClearField(usergroupentitlement.FieldExpiredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usergroupentitlement.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &UserGroupEntitlement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usergroupentitlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
