// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/usergroupentitlement"
)

// UserGroupEntitlementCreate is the builder for creating a UserGroupEntitlement entity.
type UserGroupEntitlementCreate struct {
	config
	mutation *UserGroupEntitlementMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserGroupEntitlementCreate) SetUserID(v int64) *UserGroupEntitlementCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *UserGroupEntitlementCreate) SetGroupID(v int64) *UserGroupEntitlementCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetFallbackGroupID sets the "fallback_group_id" field.
func (_c *UserGroupEntitlementCreate) SetFallbackGroupID(v int64) *UserGroupEntitlementCreate {
	_c.mutation.SetFallbackGroupID(v)
	return _c
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_c *UserGroupEntitlementCreate) SetRedeemCodeID(v int64) *UserGroupEntitlementCreate {
	_c.mutation.SetRedeemCodeID(v)
	return _c
}

// SetNillableRedeemCodeID sets the "redeem_code_id" field if the given value is not nil.
func (_c *UserGroupEntitlementCreate) SetNillableRedeemCodeID(v *int64) *UserGroupEntitlementCreate {
	if v != nil {
		_c.SetRedeemCodeID(*v)
	}
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *UserGroupEntitlementCreate) SetStartsAt(v time.Time) *UserGroupEntitlementCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_c *UserGroupEntitlementCreate) SetNillableStartsAt(v *time.Time) *UserGroupEntitlementCreate {
	if v != nil {
		_c.SetStartsAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *UserGroupEntitlementCreate) SetExpiresAt(v time.Time) *UserGroupEntitlementCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *UserGroupEntitlementCreate) SetStatus(v string) *UserGroupEntitlementCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UserGroupEntitlementCreate) SetNillableStatus(v *string) *UserGroupEntitlementCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExpiredAt sets the "expired_at" field.
func (_c *UserGroupEntitlementCreate) SetExpiredAt(v time.Time) *UserGroupEntitlementCreate {
	_c.mutation.SetExpiredAt(v)
	return _c
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_c *UserGroupEntitlementCreate) SetNillableExpiredAt(v *time.Time) *UserGroupEntitlementCreate {
	if v != nil {
		_c.SetExpiredAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserGroupEntitlementCreate) SetCreatedAt(v time.Time) *UserGroupEntitlementCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserGroupEntitlementCreate) SetNillableCreatedAt(v *time.Time) *UserGroupEntitlementCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserGroupEntitlementCreate) SetUpdatedAt(v time.Time) *UserGroupEntitlementCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserGroupEntitlementCreate) SetNillableUpdatedAt(v *time.Time) *UserGroupEntitlementCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the UserGroupEntitlementMutation object of the builder.
func (_c *UserGroupEntitlementCreate) Mutation() *UserGroupEntitlementMutation {
	return _c.mutation
}

// Save creates the UserGroupEntitlement in the database.
func (_c *UserGroupEntitlementCreate) Save(ctx context.Context) (*UserGroupEntitlement, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserGroupEntitlementCreate) SaveX(ctx context.Context) *UserGroupEntitlement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserGroupEntitlementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserGroupEntitlementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserGroupEntitlementCreate) defaults() {
	if _, ok := _c.mutation.StartsAt(); !ok {
		v := usergroupentitlement.DefaultStartsAt()
		_c.mutation.SetStartsAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := usergroupentitlement.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usergroupentitlement.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := usergroupentitlement.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserGroupEntitlementCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserGroupEntitlement.user_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "UserGroupEntitlement.group_id"`)}
	}
	if _, ok := _c.mutation.FallbackGroupID(); !ok {
		return &ValidationError{Name: "fallback_group_id", err: errors.New(`ent: missing required field "UserGroupEntitlement.fallback_group_id"`)}
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		return &ValidationError{Name: "starts_at", err: errors.New(`ent: missing required field "UserGroupEntitlement.starts_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "UserGroupEntitlement.expires_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UserGroupEntitlement.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := usergroupentitlement.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserGroupEntitlement.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserGroupEntitlement.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserGroupEntitlement.updated_at"`)}
	}
	return nil
}

func (_c *UserGroupEntitlementCreate) sqlSave(ctx context.Context) (*UserGroupEntitlement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserGroupEntitlementCreate) createSpec() (*UserGroupEntitlement, *sqlgraph.CreateSpec) {
	var (
		_node = &UserGroupEntitlement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usergroupentitlement.Table, sqlgraph.NewFieldSpec(usergroupentitlement.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(usergroupentitlement.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(usergroupentitlement.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.FallbackGroupID(); ok {
		_spec.SetField(usergroupentitlement.FieldFallbackGroupID, field.TypeInt64, value)
		_node.FallbackGroupID = value
	}
	if value, ok := _c.mutation.RedeemCodeID(); ok {
		_spec.SetField(usergroupentitlement.FieldRedeemCodeID, field.TypeInt64, value)
		_node.RedeemCodeID = &value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(usergroupentitlement.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(usergroupentitlement.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(usergroupentitlement.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExpiredAt(); ok {
		_spec.SetField(usergroupentitlement.FieldExpiredAt, field.TypeTime, value)
		_node.ExpiredAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usergroupentitlement.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usergroupentitlement.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserGroupEntitlement.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserGroupEntitlementUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserGroupEntitlementCreate) OnConflict(opts ...sql.ConflictOption) *UserGroupEntitlementUpsertOne {
	_c.conflict = opts
	return &UserGroupEntitlementUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserGroupEntitlement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserGroupEntitlementCreate) OnConflictColumns(columns ...string) *UserGroupEntitlementUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserGroupEntitlementUpsertOne{
		create: _c,
	}
}

type (
	// UserGroupEntitlementUpsertOne is the builder for "upsert"-ing
	//  one UserGroupEntitlement node.
	UserGroupEntitlementUpsertOne struct {
		create *UserGroupEntitlementCreate
	}

	// UserGroupEntitlementUpsert is the "OnConflict" setter.
	UserGroupEntitlementUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserGroupEntitlementUpsert) SetUserID(v int64) *UserGroupEntitlementUpsert {
	u.Set(usergroupentitlement.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsert) UpdateUserID() *UserGroupEntitlementUpsert {
	u.SetExcluded(usergroupentitlement.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *UserGroupEntitlementUpsert) AddUserID(v int64) *UserGroupEntitlementUpsert {
	u.Add(usergroupentitlement.FieldUserID, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *UserGroupEntitlementUpsert) SetGroupID(v int64) *UserGroupEntitlementUpsert {
	u.Set(usergroupentitlement.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsert) UpdateGroupID() *UserGroupEntitlementUpsert {
	u.SetExcluded(usergroupentitlement.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *UserGroupEntitlementUpsert) AddGroupID(v int64) *UserGroupEntitlementUpsert {
	u.Add(usergroupentitlement.FieldGroupID, v)
	return u
}

// SetFallbackGroupID sets the "fallback_group_id" field.
func (u *UserGroupEntitlementUpsert) SetFallbackGroupID(v int64) *UserGroupEntitlementUpsert {
	u.Set(usergroupentitlement.FieldFallbackGroupID, v)
	return u
}

// UpdateFallbackGroupID sets the "fallback_group_id" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsert) UpdateFallbackGroupID() *UserGroupEntitlementUpsert {
	u.SetExcluded(usergroupentitlement.FieldFallbackGroupID)
	return u
}

// AddFallbackGroupID adds v to the "fallback_group_id" field.
func (u *UserGroupEntitlementUpsert) AddFallbackGroupID(v int64) *UserGroupEntitlementUpsert {
	u.Add(usergroupentitlement.FieldFallbackGroupID, v)
	return u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *UserGroupEntitlementUpsert) SetRedeemCodeID(v int64) *UserGroupEntitlementUpsert {
	u.Set(usergroupentitlement.FieldRedeemCodeID, v)
	return u
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsert) UpdateRedeemCodeID() *UserGroupEntitlementUpsert {
	u.SetExcluded(usergroupentitlement.FieldRedeemCodeID)
	return u
}

// AddRedeemCodeID adds v to the "redeem_code_id" field.
func (u *UserGroupEntitlementUpsert) AddRedeemCodeID(v int64) *UserGroupEntitlementUpsert {
	u.Add(usergroupentitlement.FieldRedeemCodeID, v)
	return u
}

// ClearRedeemCodeID clears the value of the "redeem_code_id" field.
func (u *UserGroupEntitlementUpsert) ClearRedeemCodeID() *UserGroupEntitlementUpsert {
	u.SetNull(usergroupentitlement.FieldRedeemCodeID)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *UserGroupEntitlementUpsert) SetStartsAt(v time.Time) *UserGroupEntitlementUpsert {
	u.Set(usergroupentitlement.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsert) UpdateStartsAt() *UserGroupEntitlementUpsert {
	u.SetExcluded(usergroupentitlement.FieldStartsAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserGroupEntitlementUpsert) SetExpiresAt(v time.Time) *UserGroupEntitlementUpsert {
	u.Set(usergroupentitlement.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsert) UpdateExpiresAt() *UserGroupEntitlementUpsert {
	u.SetExcluded(usergroupentitlement.FieldExpiresAt)
	return u
}

// SetStatus sets the "status" field.
func (u *UserGroupEntitlementUpsert) SetStatus(v string) *UserGroupEntitlementUpsert {
	u.Set(usergroupentitlement.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsert) UpdateStatus() *UserGroupEntitlementUpsert {
	u.SetExcluded(usergroupentitlement.FieldStatus)
	return u
}

// SetExpiredAt sets the "expired_at" field.
func (u *UserGroupEntitlementUpsert) SetExpiredAt(v time.Time) *UserGroupEntitlementUpsert {
	u.Set(usergroupentitlement.FieldExpiredAt, v)
	return u
}

// UpdateExpiredAt sets the "expired_at" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsert) UpdateExpiredAt() *UserGroupEntitlementUpsert {
	u.SetExcluded(usergroupentitlement.FieldExpiredAt)
	return u
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (u *UserGroupEntitlementUpsert) ClearExpiredAt() *UserGroupEntitlementUpsert {
	u.SetNull(usergroupentitlement.FieldExpiredAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserGroupEntitlementUpsert) SetUpdatedAt(v time.Time) *UserGroupEntitlementUpsert {
	u.Set(usergroupentitlement.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsert) UpdateUpdatedAt() *UserGroupEntitlementUpsert {
	u.SetExcluded(usergroupentitlement.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserGroupEntitlement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserGroupEntitlementUpsertOne) UpdateNewValues() *UserGroupEntitlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usergroupentitlement.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserGroupEntitlement.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserGroupEntitlementUpsertOne) Ignore() *UserGroupEntitlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserGroupEntitlementUpsertOne) DoNothing() *UserGroupEntitlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserGroupEntitlementCreate.OnConflict
// documentation for more info.
func (u *UserGroupEntitlementUpsertOne) Update(set func(*UserGroupEntitlementUpsert)) *UserGroupEntitlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserGroupEntitlementUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserGroupEntitlementUpsertOne) SetUserID(v int64) *UserGroupEntitlementUpsertOne {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserGroupEntitlementUpsertOne) AddUserID(v int64) *UserGroupEntitlementUpsertOne {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsertOne) UpdateUserID() *UserGroupEntitlementUpsertOne {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *UserGroupEntitlementUpsertOne) SetGroupID(v int64) *UserGroupEntitlementUpsertOne {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *UserGroupEntitlementUpsertOne) AddGroupID(v int64) *UserGroupEntitlementUpsertOne {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsertOne) UpdateGroupID() *UserGroupEntitlementUpsertOne {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.UpdateGroupID()
	})
}

// SetFallbackGroupID sets the "fallback_group_id" field.
func (u *UserGroupEntitlementUpsertOne) SetFallbackGroupID(v int64) *UserGroupEntitlementUpsertOne {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.SetFallbackGroupID(v)
	})
}

// AddFallbackGroupID adds v to the "fallback_group_id" field.
func (u *UserGroupEntitlementUpsertOne) AddFallbackGroupID(v int64) *UserGroupEntitlementUpsertOne {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.AddFallbackGroupID(v)
	})
}

// UpdateFallbackGroupID sets the "fallback_group_id" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsertOne) UpdateFallbackGroupID() *UserGroupEntitlementUpsertOne {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.UpdateFallbackGroupID()
	})
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *UserGroupEntitlementUpsertOne) SetRedeemCodeID(v int64) *UserGroupEntitlementUpsertOne {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// AddRedeemCodeID adds v to the "redeem_code_id" field.
func (u *UserGroupEntitlementUpsertOne) AddRedeemCodeID(v int64) *UserGroupEntitlementUpsertOne {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.AddRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsertOne) UpdateRedeemCodeID() *UserGroupEntitlementUpsertOne {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// ClearRedeemCodeID clears the value of the "redeem_code_id" field.
func (u *UserGroupEntitlementUpsertOne) ClearRedeemCodeID() *UserGroupEntitlementUpsertOne {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.ClearRedeemCodeID()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *UserGroupEntitlementUpsertOne) SetStartsAt(v time.Time) *UserGroupEntitlementUpsertOne {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsertOne) UpdateStartsAt() *UserGroupEntitlementUpsertOne {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserGroupEntitlementUpsertOne) SetExpiresAt(v time.Time) *UserGroupEntitlementUpsertOne {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsertOne) UpdateExpiresAt() *UserGroupEntitlementUpsertOne {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetStatus sets the "status" field.
func (u *UserGroupEntitlementUpsertOne) SetStatus(v string) *UserGroupEntitlementUpsertOne {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsertOne) UpdateStatus() *UserGroupEntitlementUpsertOne {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.UpdateStatus()
	})
}

// SetExpiredAt sets the "expired_at" field.
func (u *UserGroupEntitlementUpsertOne) SetExpiredAt(v time.Time) *UserGroupEntitlementUpsertOne {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.SetExpiredAt(v)
	})
}

// UpdateExpiredAt sets the "expired_at" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsertOne) UpdateExpiredAt() *UserGroupEntitlementUpsertOne {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.UpdateExpiredAt()
	})
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (u *UserGroupEntitlementUpsertOne) ClearExpiredAt() *UserGroupEntitlementUpsertOne {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.ClearExpiredAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserGroupEntitlementUpsertOne) SetUpdatedAt(v time.Time) *UserGroupEntitlementUpsertOne {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsertOne) UpdateUpdatedAt() *UserGroupEntitlementUpsertOne {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserGroupEntitlementUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserGroupEntitlementCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserGroupEntitlementUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserGroupEntitlementUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserGroupEntitlementUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserGroupEntitlementCreateBulk is the builder for creating many UserGroupEntitlement entities in bulk.
type UserGroupEntitlementCreateBulk struct {
	config
	err      error
	builders []*UserGroupEntitlementCreate
	conflict []sql.ConflictOption
}

// Save creates the UserGroupEntitlement entities in the database.
func (_c *UserGroupEntitlementCreateBulk) Save(ctx context.Context) ([]*UserGroupEntitlement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserGroupEntitlement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserGroupEntitlementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserGroupEntitlementCreateBulk) SaveX(ctx context.Context) []*UserGroupEntitlement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserGroupEntitlementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserGroupEntitlementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserGroupEntitlement.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserGroupEntitlementUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserGroupEntitlementCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserGroupEntitlementUpsertBulk {
	_c.conflict = opts
	return &UserGroupEntitlementUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserGroupEntitlement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserGroupEntitlementCreateBulk) OnConflictColumns(columns ...string) *UserGroupEntitlementUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserGroupEntitlementUpsertBulk{
		create: _c,
	}
}

// UserGroupEntitlementUpsertBulk is the builder for "upsert"-ing
// a bulk of UserGroupEntitlement nodes.
type UserGroupEntitlementUpsertBulk struct {
	create *UserGroupEntitlementCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserGroupEntitlement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserGroupEntitlementUpsertBulk) UpdateNewValues() *UserGroupEntitlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usergroupentitlement.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserGroupEntitlement.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserGroupEntitlementUpsertBulk) Ignore() *UserGroupEntitlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserGroupEntitlementUpsertBulk) DoNothing() *UserGroupEntitlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserGroupEntitlementCreateBulk.OnConflict
// documentation for more info.
func (u *UserGroupEntitlementUpsertBulk) Update(set func(*UserGroupEntitlementUpsert)) *UserGroupEntitlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserGroupEntitlementUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserGroupEntitlementUpsertBulk) SetUserID(v int64) *UserGroupEntitlementUpsertBulk {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserGroupEntitlementUpsertBulk) AddUserID(v int64) *UserGroupEntitlementUpsertBulk {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsertBulk) UpdateUserID() *UserGroupEntitlementUpsertBulk {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *UserGroupEntitlementUpsertBulk) SetGroupID(v int64) *UserGroupEntitlementUpsertBulk {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *UserGroupEntitlementUpsertBulk) AddGroupID(v int64) *UserGroupEntitlementUpsertBulk {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsertBulk) UpdateGroupID() *UserGroupEntitlementUpsertBulk {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.UpdateGroupID()
	})
}

// SetFallbackGroupID sets the "fallback_group_id" field.
func (u *UserGroupEntitlementUpsertBulk) SetFallbackGroupID(v int64) *UserGroupEntitlementUpsertBulk {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.SetFallbackGroupID(v)
	})
}

// AddFallbackGroupID adds v to the "fallback_group_id" field.
func (u *UserGroupEntitlementUpsertBulk) AddFallbackGroupID(v int64) *UserGroupEntitlementUpsertBulk {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.AddFallbackGroupID(v)
	})
}

// UpdateFallbackGroupID sets the "fallback_group_id" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsertBulk) UpdateFallbackGroupID() *UserGroupEntitlementUpsertBulk {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.UpdateFallbackGroupID()
	})
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *UserGroupEntitlementUpsertBulk) SetRedeemCodeID(v int64) *UserGroupEntitlementUpsertBulk {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// AddRedeemCodeID adds v to the "redeem_code_id" field.
func (u *UserGroupEntitlementUpsertBulk) AddRedeemCodeID(v int64) *UserGroupEntitlementUpsertBulk {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.AddRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsertBulk) UpdateRedeemCodeID() *UserGroupEntitlementUpsertBulk {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// ClearRedeemCodeID clears the value of the "redeem_code_id" field.
func (u *UserGroupEntitlementUpsertBulk) ClearRedeemCodeID() *UserGroupEntitlementUpsertBulk {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.ClearRedeemCodeID()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *UserGroupEntitlementUpsertBulk) SetStartsAt(v time.Time) *UserGroupEntitlementUpsertBulk {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsertBulk) UpdateStartsAt() *UserGroupEntitlementUpsertBulk {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserGroupEntitlementUpsertBulk) SetExpiresAt(v time.Time) *UserGroupEntitlementUpsertBulk {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsertBulk) UpdateExpiresAt() *UserGroupEntitlementUpsertBulk {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetStatus sets the "status" field.
func (u *UserGroupEntitlementUpsertBulk) SetStatus(v string) *UserGroupEntitlementUpsertBulk {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsertBulk) UpdateStatus() *UserGroupEntitlementUpsertBulk {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.UpdateStatus()
	})
}

// SetExpiredAt sets the "expired_at" field.
func (u *UserGroupEntitlementUpsertBulk) SetExpiredAt(v time.Time) *UserGroupEntitlementUpsertBulk {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.SetExpiredAt(v)
	})
}

// UpdateExpiredAt sets the "expired_at" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsertBulk) UpdateExpiredAt() *UserGroupEntitlementUpsertBulk {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.UpdateExpiredAt()
	})
}

// ClearExpiredAt clears the value of the "expired_at" field.
func (u *UserGroupEntitlementUpsertBulk) ClearExpiredAt() *UserGroupEntitlementUpsertBulk {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.ClearExpiredAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserGroupEntitlementUpsertBulk) SetUpdatedAt(v time.Time) *UserGroupEntitlementUpsertBulk {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserGroupEntitlementUpsertBulk) UpdateUpdatedAt() *UserGroupEntitlementUpsertBulk {
	return u.Update(func(s *UserGroupEntitlementUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserGroupEntitlementUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserGroupEntitlementCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserGroupEntitlementCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserGroupEntitlementUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
